/** Template content shared by CLI generator and download API. */

export {
  ASSESSMENT_COLUMN_BY_TYPE,
  ASSESSMENT_COLUMNS,
  ATTENDANCE_COLUMNS,
  BACKUP_STAFF_COLUMNS,
  CALENDAR_COLUMNS,
  CALENDAR_LEGACY_COLUMNS,
  FORBIDDEN_IMPORT_SHEETS,
  IMPORT_SHEET_NAMES,
  SCHOOL_SETUP_COLUMNS,
  SHEET_NAMES,
  STUDENT_COLUMNS,
  STAFF_COLUMNS,
  STAFF_LEGACY_COLUMNS,
  TEACHER_COLUMNS,
  type SheetName,
} from "@/lib/import/sheet-spec";

export const IMPORT_TEMPLATE_FILENAME = "fwis-school-data-import-template.xlsx";

export const INSTRUCTIONS_LINES = [
  "FWIS School Data Import Template (Staff + Students)",
  "",
  "Prerequisites (must already exist in the database — import will abort if missing):",
  "  • School (match school_city + school_state)",
  "  • Academic year linked to that school (match academic_year name on each row)",
  "  • Default app users for the school (Create default app users when adding the school)",
  "  • Lookup data: roles, grades, sections, genders (npm run db:seed)",
  "",
  "Fill one workbook per school per academic year, then run:",
  "  npm run import:school -- --file path/to/file.xlsx --dry-run",
  "  npm run import:school -- --file path/to/file.xlsx",
  "",
  "Always run --dry-run first: it validates every foreign key against the database",
  "without writing (school, year, roles, app users, grades, sections, genders).",
  "",
  "Or download a fresh template from Backup → Import template in the FWIS app.",
  "",
  "Sheet order (do not rename sheets):",
  "  1. Staff     — one row per principal/admin/teacher/substitute (login derived)",
  "  2. Students  — one row per enrolled student",
  "",
  "Rules:",
  "  • Only Staff + Students (plus Instructions). Do NOT add other sheets",
  "  • Rejected if present: School_Setup, Teachers (legacy), Attendance, Assessments, Calendar",
  "  • Import does NOT create schools, academic years, or app_users",
  "  • school_city + school_state + academic_year must match on every row",
  "  • Staff login is derived (do not enter user_id):",
  "      Principal   → {schoolCode}.principal           e.g. hou.principal",
  "      School Admin→ {schoolCode}.[m/f].admin         e.g. hou.m.admin",
  "      Teacher     → {schoolCode}.[b/g].g{grade}      e.g. hou.b.g1",
  "      Substitute  → {schoolCode}.[m/f].sub           e.g. hou.m.sub",
  "  • Those logins must already exist (from Create default app users)",
  "  • Staff.staff_role: Principal, School Admin, Teacher, or Substitute",
  "  • Principal / School Admin / Substitute: leave grade/section blank; set gender",
  "  • Teacher: grade + section required; only one Teacher per grade + section",
  "  • Staff.gender: required for Principal, School Admin, Substitute; optional for Teacher",
  "  • Students.grade + section must match a Staff Teacher classroom",
  "  • student_id: HOU-B1 (city code + B/G + number); blank = auto-assign",
  "  • grade: 1–6 or Grade 1 … Grade 6",
  "  • section: Boys or Girls",
  "  • gender: MALE or FEMALE (must match section for students)",
  "  • See docs/DATA_IMPORT.md for full column reference",
  "  • Delete all example rows before importing real data",
  "",
  "Example rows are provided on each sheet — replace with your school data.",
];

export const EXAMPLE_STAFF = [
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    first_name: "Imran",
    last_name: "Principal",
    email: "imran.principal@email.com",
    phone: "555-3000",
    staff_role: "Principal",
    gender: "MALE",
    grade: "",
    section: "",
  },
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    first_name: "Ali",
    last_name: "Boys Admin",
    email: "ali.admin@email.com",
    phone: "555-3003",
    staff_role: "School Admin",
    gender: "MALE",
    grade: "",
    section: "",
  },
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    first_name: "Muhammad",
    last_name: "Usman Khan",
    email: "muhammad.usman@email.com",
    phone: "555-3001",
    staff_role: "Teacher",
    gender: "MALE",
    grade: "1",
    section: "Boys",
  },
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    first_name: "Fatima",
    last_name: "Ali Khan",
    email: "fatima.ali@email.com",
    phone: "555-3002",
    staff_role: "Teacher",
    gender: "FEMALE",
    grade: "1",
    section: "Girls",
  },
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    first_name: "Omar",
    last_name: "Substitute",
    email: "omar.sub@email.com",
    phone: "555-3099",
    staff_role: "Substitute",
    gender: "MALE",
    grade: "",
    section: "",
  },
];

/** @deprecated Use EXAMPLE_STAFF */
export const EXAMPLE_TEACHERS = EXAMPLE_STAFF;

export const EXAMPLE_STUDENTS = [
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    student_id: "HOU-B1",
    first_name: "Ahmed",
    last_name: "Khan",
    gender: "MALE",
    email_address: "parent.khan@email.com",
    grade: "1",
    section: "Boys",
    street_address: "123 Main St",
    city: "Houston",
    state_province: "TX",
    zip_postal_code: "77001",
    country: "USA",
    father_guardian_first_name: "Ali",
    father_guardian_last_name: "Khan",
    father_parental_responsibility: "Yes",
    father_mobile_whatsapp_number: "555-1001",
    mother_guardian_first_name: "Sara",
    mother_guardian_last_name: "Khan",
    mother_parental_responsibility: "Yes",
    mother_mobile_whatsapp_number: "555-1002",
    enrollment_date: "2024-09-08",
  },
  {
    school_city: "Houston",
    school_state: "TX",
    academic_year: "2024-2025",
    student_id: "HOU-G1",
    first_name: "Aisha",
    last_name: "Ali",
    gender: "FEMALE",
    email_address: "parent.ali@email.com",
    grade: "1",
    section: "Girls",
    street_address: "456 Oak Ave",
    city: "Houston",
    state_province: "TX",
    zip_postal_code: "77002",
    country: "USA",
    father_guardian_first_name: "Omar",
    father_guardian_last_name: "Ali",
    father_parental_responsibility: "Yes",
    father_mobile_whatsapp_number: "555-2001",
    mother_guardian_first_name: "Maryam",
    mother_guardian_last_name: "Ali",
    mother_parental_responsibility: "Yes",
    mother_mobile_whatsapp_number: "555-2002",
    enrollment_date: "2024-09-08",
  },
];
