/** Re-exports for scripts/import — keep CLI imports stable. */

export {
  ASSESSMENT_COLUMN_BY_TYPE,
  ASSESSMENT_COLUMNS,
  ATTENDANCE_COLUMNS,
  BACKUP_STAFF_COLUMNS,
  CALENDAR_COLUMNS,
  CALENDAR_LEGACY_COLUMNS,
  FORBIDDEN_IMPORT_SHEETS,
  IMPORT_SHEET_NAMES,
  SCHOOL_SETUP_COLUMNS,
  SHEET_NAMES,
  STUDENT_COLUMNS,
  STAFF_COLUMNS,
  STAFF_LEGACY_COLUMNS,
  TEACHER_COLUMNS,
  type SheetName,
} from "../../src/lib/import/sheet-spec";

export {
  EXAMPLE_STUDENTS,
  EXAMPLE_TEACHERS,
  EXAMPLE_STAFF,
  IMPORT_TEMPLATE_FILENAME,
  INSTRUCTIONS_LINES,
} from "../../src/lib/import/import-template-content";
